-- Creates tables for the payroll system

-- Drops tables in reverse order (to consider foreign key dependencies)
DROP TABLE payroll_rates CASCADE CONSTRAINTS;
DROP TABLE monthly_work_norms CASCADE CONSTRAINTS;
DROP TABLE tax_exemptions CASCADE CONSTRAINTS;
DROP TABLE employee_salaries CASCADE CONSTRAINTS;
DROP TABLE employees CASCADE CONSTRAINTS;

-- Employees table
CREATE TABLE employees (
    employee_id      NUMBER PRIMARY KEY,
    first_name      VARCHAR2(100),
    last_name       VARCHAR2(100),
    hire_date       DATE,
    is_union_member CHAR(1) DEFAULT 'N' NOT NULL CHECK (is_union_member IN ('Y', 'N')),
    exemption_code  VARCHAR2(50) REFERENCES tax_exemptions(exemption_code)
);

-- Employee salaries table
CREATE TABLE employee_salaries (
    salary_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    employee_id     NUMBER NOT NULL REFERENCES employees(employee_id),
    salary_month    DATE NOT NULL,
    gross_salary    NUMBER(10, 2) NOT NULL,
    vacation_days   NUMBER DEFAULT 0,
    overtime_hours  NUMBER DEFAULT 0,
    CONSTRAINT uq_employee_salary UNIQUE (employee_id, salary_month)
);

-- Tax exemptions table
CREATE TABLE tax_exemptions (
    exemption_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    exemption_code  VARCHAR2(50) UNIQUE NOT NULL,
    exemption_amount NUMBER(10, 2) NOT NULL
);

-- Monthly work norms table
CREATE TABLE monthly_work_norms (
    month_id        NUMBER(2) NOT NULL CHECK (month_id BETWEEN 1 AND 12),
    work_year       NUMBER(4) NOT NULL,
    work_days_norm  NUMBER(2) NOT NULL,
    work_hours_norm NUMBER(3) NOT NULL,
    CONSTRAINT pk_monthly_work_norms PRIMARY KEY (month_id, work_year)
);

-- Payroll rates table
CREATE TABLE payroll_rates (
    rate_code        VARCHAR2(100) NOT NULL,
    sector           VARCHAR2(20) NOT NULL CHECK (sector IN ('public', 'private')),
    min_gross_amount NUMBER(10, 2),
    max_gross_amount NUMBER(10, 2),
    rate_value       NUMBER(5, 4) NOT NULL,
    fixed_amount     NUMBER(10, 2) DEFAULT 0,
    description      VARCHAR2(255),
    CONSTRAINT pk_payroll_rates PRIMARY KEY (rate_code, sector, min_gross_amount, max_gross_amount)
);
